### PR TITLE
fix dockerfile so that it builds

### PR DESCRIPTION
**Pull request by vicentebolea**
I have noticed that the current dockerfile does not work, this changes allow it to pass. Tested in Clara AGX.

### CODE REVIEW

**Comment by vicentebolea** [comment]
The errors come one by one the first one is after running `./dev_container build`:

```
.94         error: subprocess-exited-with-error                                                                                                                                                             [5/258]
17.94                                                                                                                                                                                                                
17.94         × Building wheel for pycairo (pyproject.toml) did not run successfully.                                                                                                                                
17.94         │ exit code: 1                                                                                                                                                                                         
17.94         ╰─> [12 lines of output]                                                                                                                                                                               
17.94             running bdist_wheel                                                                                                                                                                                
17.94             running build
17.94             running build_py
17.94             creating build
17.94             creating build/lib.linux-aarch64-cpython-310
17.94             creating build/lib.linux-aarch64-cpython-310/cairo
17.94             copying cairo/__init__.py -> build/lib.linux-aarch64-cpython-310/cairo
17.94             copying cairo/__init__.pyi -> build/lib.linux-aarch64-cpython-310/cairo
17.94             copying cairo/py.typed -> build/lib.linux-aarch64-cpython-310/cairo
17.94             running build_ext
17.94             'pkg-config' not found.
17.94             Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']
17.94             [end of output]
17.94       
17.94         note: This error originates from a subprocess, and is likely not a problem with pip.
17.94         ERROR: Failed building wheel for pycairo
17.94       Failed to build pycairo
17.94       ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
17.94       
17.94       [notice] A new release of pip is available: 23.3.2 -> 24.0
17.94       [notice] To update, run: python3 -m pip install --upgrade pip
17.94       [end of output]
17.94   
17.94   note: This error originates from a subprocess, and is likely not a problem with pip.
17.94 error: subprocess-exited-with-error
17.94 
17.94 × pip subprocess to install build dependencies did not run successfully.
17.94 │ exit code: 1
17.94 ╰─> See above for output.
17.94 
17.94 note: This error originates from a subprocess, and is likely not a problem with pip.
17.95 
17.95 [notice] A new release of pip is available: 23.3.2 -> 24.0
17.95 [notice] To update, run: python3 -m pip install --upgrade pip
```
pkg-config is also needed later by a pip pkg, same as liblges2

**Comment by jjomier** [comment]
This is strange we were getting the same error but this commit fixed it: https://github.com/nvidia-holoscan/holohub/commit/8255cc046a6dccb186460795c45a14cda3402ce2

Let me investigate on CAGX

**Comment by jjomier** [comment]
@vicentebolea I'm not able to replicate the issue with the current main branch. Can you try to delete the docker images and try again? Which Holoscan base image is the script pulling?

**Comment by vicentebolea** [comment]
You are correct this is not happening anymore, it appears that it was resolved in #215. Closing this

**Pull request closed without merging**
