### PR TITLE
Introduce Rivermax Manager to ANO for RTP Stream Handling with IPO Support

### PR DESCRIPTION
**Pull request by ronyrad**
### **Description**

This merge request introduces the **Rivermax Manager** to the **Advanced Network Operator (ANO)**. The new manager enhances ANO’s capabilities by enabling effective handling of **RTP streams** with **Inline Packet Ordering (IPO)**, ensuring seamless reception of the same stream from multiple redundant paths, thus improving network reliability and efficiency.

**Key details:**

- The integrated **Rivermax Manager** currently supports **RX operations** only.
- Detailed instructions on building and using the operator are available in the accompanying **README**.
- The **Rivermax Manager** code is located in `managers/rivermax`.
-  **ANO Networking Bench application** RX operator functionality of DPDK and Rivermax is common in `default_bench_rx.h`, while DOCA is in `doca_bench_opt_rx.h`.
- The updated common **Dockerfile** for all manager types is located in `operators/advanced_network` folder.

### **How It Works**

- The **Rivermax Manager** runs multiple services, with each service handling a separate receiver queue.
- These services (referred to as `RmaxIPOReceiverService`) configure and execute **receive nodes** (`IPOReceiverNode`), responsible for stream handling and statistics management.
- Receive nodes run on isolated CPUs by setting processor affinity to optimize performance.
- Receive nodes provide chunks of packets, which are converted into **ANO packet bursts** and pushed to the bursts queue.
- Applications using **Rivermax in ANO** will read bursts from this queue for further processing.

---

### **Additional Features and Fixes**

1. **Support for Multiple ANO Managers**
   - **Code Changes:**
     - Introduces the `AnoMgrFactory` class to support multiple ANO managers.
     - Adheres to both Factory and Singleton design patterns, ensuring a single, globally accessible instance to dynamically create manager objects based on specific needs.
     - Allows explicit type setting via a dedicated Enum variable or explicit selection through parsing of `AdvNetConfigYaml`.
     - Provides streamlined access to the active manager via `AnoMgrFactory::get_active_manager()`, returning a reference to the currently active manager.
  
   - **Build System Changes:**
     - Added `CMakeLists.txt` files at all folder levels to support the new build system.
     - Each ANO manager has its own `CMakeLists.txt` and is built as a shared library, only if enabled by configuration.
     - For instance, compiling with `-DANO_MGR="dpdk rivermax"` enables support for both DPDK and Rivermax managers.
       ```
       ./run build adv_networking_bench --configure-args "-DANO_MGR=dpdk rivermax"
       ```
     - Simplifies management of multiple ANO managers, making it easier to extend and configure the system based on varying network configurations and requirements.
     - The default manager selection order is: `dpdk` (if enabled), `doca` (if enabled), `rivermax`.

2. **Enhanced Logging and YAML Configuration Parsing**
   - Added log level support for various managers, including DOCA, DPDK, and Rivermax.
   - Refactored YAML configuration parsing for improved readability, maintainability, and performance:
     - Introduced new parsing functions for flow, memory region, RX queue, and TX queue configurations.
     - Enhanced error handling in all parsing functions.
     - Updated the decode function to utilize the new parsing functions.
     - Extracted common queue parsing logic into a separate function.

3. **Dynamic Output Port Naming**
   - Added an option to set output port names via the `AdvNetworkOpRx` constructor:
     - Introduced a new constructor to `AdvNetworkOpRx` for setting output port names.
     - Implemented `adv_net_get_port_names` function to parse configuration and compile a list of output port names.
     - Updated the setup function in `AdvNetworkOpRx` to use dynamic output port names, with added logging for each port.

---

### CODE REVIEW

**Review by cliffburdick — APPROVED** [review]
Approved, but still need to test

**Comment by cliffburdick** [comment]
@jjomier can you review this while @agirault is out?

**Comment by jjomier** [comment]
@cliffburdick I don't have the technical expertise to do a proper review. 
Can someone with expertise do it?

**Comment by cliffburdick** [comment]
@e-ago do you mind reviewing?

**Review by cliffburdick — APPROVED** [review]

**Pull request closed without merging**
