### PR TITLE
Vila replayer

### PR DESCRIPTION
**Pull request by maximilianofir**
- allow replaying videos in ViLa_live application. 
- allows for testing ViLa on a variety of videos from different domains

### CODE REVIEW

**Review by tbirdso — COMMENTED** [review]
Code changes look good to me. Could we please add the following:
- Document the CLI in the app README;
- Add a v4l2 section in the app YAML with default settings for the user to update, similar to https://github.com/nvidia-holoscan/holohub/blob/3067096ad0ab2bd42a07c03b7a97f1d2d5bad8ee/applications/body_pose_estimation/body_pose_estimation.yaml#L20

**Comment by NigelNelson** [comment]
Are these changes enabling the app to use GXF entities from the video replayer?
If this is the case, I find it easier to mount an MP4 using FFMPEG and V4L2 loopback than go through the GXF entity creation scripts.

Regardless, if replayer support is desired I think the README.md should link to where to find information on how to use the replayer.

**Comment by maximilianofir** [comment]
Hi Nigel,
That makes more sense. I was not aware of the V4L2 loopback option until yesterday.
Will adjust the MR in favor of this workflow.

**Comment by jjomier** [comment]
@NigelNelson @maximilianofir what is the status of this MR?

**Review by tbirdso — APPROVED** [review]
Code LGTM. Would like to wait for @NigelNelson 's review as well before merge

**Comment by NigelNelson** [comment]
Looks good to me! Only a small nit: it would be nice to rename the new "setup instructions" to a "video options" or something similar, as otherwise there are two "setup instruction" settings.

**Review by NigelNelson — APPROVED** [review]

**Comment by maximilianofir** [comment]
Thanks all, I renamed the section to Video Options.

**Pull request merged**
